### ISSUE TITLE
Webview scrolling issue 

### ISSUE THREAD

**Issue by LightDestory** [LightDestory/FastHub-RE#10]
Scrolling on a markdown content isn't fluid. The scroll jump at the start/end of the content

**Comment by zeromake** [comment]
@LightDestory 
[change](https://github.com/zeromake/FastHub/commit/9871e589b9f5c1f31d6a4faf69e977eb8e7c821c)
try to use rx debounce webview onScrollChanged event, the effect is good, but the code is too ugly, is there a better solution

**Comment by LightDestory** [comment]
I will try as soon as I can get the new codebase working.

Thanks for the help :)

**Comment by LightDestory** [comment]
Kinda fixed by changed the implementation :)
