### ISSUE TITLE
[BUG]Wrong url is used when see commit info from issue or PR

### ISSUE THREAD

**Issue by yyjdelete** [LightDestory/FastHub-RE#13]
**FastHub Version:**  4.7.4
**Android Version:**  11
**Device Information:**  
- MANUFACTURER:   
- BRAND:   
- MODEL:   
---
Try to open #6 and click `4e69f63` 
it's expected to see `LightDestory/FastHub-RE` but see `repos/LightDestory` and `Not Found`(Open any commit from `Commits` tab or issue content works well)

**Comment by LightDestory** [comment]
This issue is not present on the new code base, probably fixed by @zeromake.

I am closing this :)

Soon there will be a new release of fasthub-re.
