### ISSUE TITLE
[FR] Add PAT (personal access token) login back

### ISSUE THREAD

**Issue by jack1142** [LightDestory/FastHub-RE#20]
**Is your feature request related to a problem? Please describe.**
Usage of oauth requires approval from every organisation you're in which takes time and may not be able to happen. And what's worse, I have to authorize app owned by you who can then, theoretically, do anything I can with it. If I would be able to use a PAT, it would only have to be stored by the app and no 3rd-party is involved (assuming I verify code of this application anyway). 

**Describe the solution you'd like**
Add back an option to login with a PAT. 

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
N/A

**Comment by jack1142** [comment]
I'm guessing it's been done because of this *but* this post actually mentions that using PAT is one of the recommended alternatives:
https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

**Comment by LightDestory** [comment]
The feature as already been restored on the working in progress version. You can try yourself by downloading the artifact on the github action page :)

These version are currently for debugging and are signed with the original FastHub Demo keys and appID so when you login you will be prompted to give access to FastHub Demo.

**Comment by LightDestory** [comment]
A releaseFastHub-Re has been published, you can try the new one.

Remmeber to uninstall the old one and install the new one, just for this time. 

Signature keys has been changes since the first FastHub-RE release and it will not install over the old one
