### ISSUE TITLE
read:packages error toast when using oauth login

### ISSUE THREAD

**Issue by TheFern2** [LightDestory/FastHub-RE#36]
Getting an error for package read permission. I didn't see this on the permissions scopes, so probably just need to be added so user can authorize it as a scope.

**Comment by LightDestory** [comment]
The permission is ```android.permission.READ_LOGS```?

**Comment by TheFern2** [comment]
Sorry should have more clear, I believe this is not on the oauth scopes.

https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps

Getting a read:packages error on the latest release.

**Comment by LightDestory** [comment]
Oauth can't access packages listing.

For the best experience use a Personal Access Token (it is displayed as
recommended)

Il Mar 19 Apr 2022, 19:11 Fernando B ***@***.***> ha scritto:

**Comment by TheFern2** [comment]
I thought it wasn't being requested. I see read:packages on oauth permissions. Should work with oauth imo, though I could be wrong.

**Comment by LightDestory** [comment]
Hmm I will check, maybe I forgot to update the scope string.

I don't use oauth login due to Organizzation issues, oauth application
needs to request permission per organisation. Using a Token makes
everything easier xD

Thanks for the feedback


Il Mar 19 Apr 2022, 22:26 Fernando B ***@***.***> ha scritto:

**Comment by TheFern2** [comment]
Yeah no worries don't mind me I just report things to make things better in the future. I don't care much for packages tbh so this issue isn't much about packages but more about the error toast when using oauth (will rename issue), but anytime I go to a repo I get the read:packages error toast. I do agree tokens make it easier. I will switch to it for now to avoid seeing the toast.

**Comment by LightDestory** [comment]
We can close this thanks to [0842881](https://github.com/LightDestory/FastHub-RE/commit/0842881983e03b561bc65bada6ff6af60c379f9b).

Re-open if you find any issues.

To test out right away the changes you can wait for the GitHub Action and download the artifact from there. Be aware that github action offers debug builds that use debugging keys. So you will be prompt to give permission to the "FastHub Demo" OAuth application.

This fix will be on 4.7.8, when released.

**Comment by TheFern2** [comment]
Thanks for the fix! I'll test it out asap.
