### ISSUE TITLE
[BUG] Menus align to the left in Issues

### ISSUE THREAD

**Issue by yephny** [LightDestory/FastHub-RE#49]
Created, Participaing etc. have some empty space on the right, they can be centered to have equal distance between each item.

FastHub-RE Version: 4.7.7    
Android Version:  10

**Comment by LightDestory** [comment]
Please provide screenshot and device details such as screen size.

**Comment by yephny** [comment]
I don't remember why I created this issue. It could be that I wasn't aware you could move the buttons I mentioned in my post horizontally.
